### ISSUE TITLE
Materials Summary Bug

### ISSUE THREAD

**Issue by abrechts** [abrechts/Phoenix-ELN#18]
### Discussed in https://github.com/abrechts/Phoenix-ELN/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **Demydoff** October  2, 2024</sup>
![photo_2024-10-02_18-18-01](https://github.com/user-attachments/assets/d0e39884-a821-4e65-bfb2-38211b1ed0a9)
![photo_2024-10-02_18-17-59](https://github.com/user-attachments/assets/8da589f9-78d1-4ed0-a379-4ce4c03a7a8d)
![photo_2024-10-02_18-17-59 (2)](https://github.com/user-attachments/assets/6c789ee9-382a-4ce2-ba01-989b953d74b4)
![photo_2024-10-02_18-18-00](https://github.com/user-attachments/assets/a0dea7a8-905b-421a-9e77-6f77b772b651)
</div>

**Comment by abrechts** [comment]
@Demydoff: Thanks for reporting this issue. The message behind your screen shots was mostly understood, but sometimes it was not fully clear. An additional summary in words of what was seen against what was expected would help to understand the extent of an issue more quickly and precisely in the future, as below. It also helps to more easily determine if the issue is fixed later on. Thanks.

_Expected_ summary dialog behavior of a molar reagent solution with an assumed density of 0.5:

- 5.00 ml (protocol)  --> 2.50 g (summary)         Note: Currently reagent summary amounts always are displayed in grams
- 2.50 g (protocol)    --> 2.50 g (summary)         Note: Display as weight checked

_Current_ behavior:

- 5.00 ml (protocol)  --> 5.00 g (summary)
- 2.50 g (protocol)   -->  5.00 g (summary)
 
This is confirmed as a bug. The fix will be assigned to the next release, if possible.

**Comment by Demydoff** [comment]
I apologize for the lack of comments on the pictures. There was no time. Yes, you understood everything correctly. The program does not take into account the density

**Comment by abrechts** [comment]
No problem, thanks for your feedback.

**Comment by abrechts** [comment]
The reported issue is fixed now. Additionally, the unit conversion rules were changed for molar reagent solutions: These now are always converted to volume units instead of weights in the summary (which makes more sense for a liquid), while solid reagent entries remain listed in weight units, as before. Thus the new expected behavior for the above molar solution example with a density of 0.5 will be:

Expected behavior:

- 5.00 mL (protocol)  --> 5.00 mL (summary)
- 2.50 g (protocol)    --> 5.00 mL (summary) 

These changes are planned to be part of the next release.
